
export const ADDTODO = "ADDTODO";
export const TOGGLETODO = "TOGGLETODO";
export const DELETETODO = "DELETETODO";
export const CLEARTODO = "CLEARTODO";
export const DATAFROMLOCALSTORAGE = "DATAFROMLOCALSTORAGE";
